config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end 
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message
  before_action :find_comments, only: [:edit, :update, :destroy]

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = 'Comment created'
      redirect_to message_path(@message)
    else
      flash[:warning] = 'Error creating comment'
      render 'new'
    end
  end

def edit
end

def update
  if @comment.update(comment_params)
    flash[:success] = 'Comment updated.'
    redirect_to message_path(@message)
  else
    flash[:danger] = 'Error updating comment.'
    render 'edit'
  end
end

def destroy
  @comment.destroy
  flash[:danger] = 'Comment deleted.'
  redirect_to @message
end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def find_message
      @message = Message.find(params[:message_id])
    end

    def find_comments
      @comment = @message.comments.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order('created_at DESC')
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = 'Message Created'
      redirect_to root_path
    else
      flash[:warning] = "Error creating Message"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      flash[:success] = 'Message Updated'
      redirect_to @message
    else
      flash[:warning] = 'Error updating message'
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    flash[:danger] = 'Message destroyed'
    redirect_to root_path
  end

  private

    def message_params
      params.require(:message).permit(:title, :description, :user_id)
    end

    def find_message
      @message = Message.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-posted-by">Posted by: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago.</p>

  <div class="links">
    <% if comment.user == current_user %>
      <%= link_to 'Edit', edit_message_comment_path(comment.message, comment) %>
      <%= link_to 'Delete', message_comment_path(comment.message, comment), method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: 'Comment' %>
  <%= f.button :submit, class: 'btn-custom' %>
<% end  %>

app/views/comments/edit.html.erb
<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: 'Comment' %>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'parts/navbar' %>
    <%= render 'parts/flash' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: 'Message Title' %>
  <%= f.input :description %>
  <%= f.button :submit, class: 'btn-custom' %>
<% end %>

app/views/messages/edit.html.erb
<h2>Edit Message</h2>
<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
  <div class="col-md-4">
    <div class="message">
      <h2 class="message-title"><%= message.title %></h2>
      <%= link_to 'View Message', message_path(message), class: 'btn-custom' %>
    </div>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>New Message</h2>
  <%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="message-show">
    <h2><%= @message.title %></h2>
    <p class="message-posted-by">Posted by: <%=@message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago.</p>
    <p class="message-desc"><%= @message.description %></p>


    <h3>Comments:</h3>
    <%= render @message.comments %>

    <% if user_signed_in? %>
      <h3 class="reply-to-msg">Reply to message:</h3>
      <%= render 'comments/form' %>
    <% end %>

    <div class="links btn-group">
      <%= link_to 'Back', root_path, class: 'btn btn-default' %>
      <% if user_signed_in? %>
        <% if @message.user == current_user %>
          <%= link_to 'Edit', edit_message_path(@message), class: 'btn btn-default' %>
          <%= link_to 'Delete', message_path(@message), class: 'btn btn-default', method: :delete, data: {confirm: 'are you sure?'} %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/parts/_flash.html.erb
<% flash.each do |type, message|  %>
  <p class='alert alert-<%= type %>'><%= message %></p>
<% end %>

app/views/parts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Message Board", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
      <% if user_signed_in? %>
          <p><%= link_to 'New Message', new_message_path, class: 'navbar-right navbar-text navbar-link' %></p>
      <% end %>
  </div>
</div>